### ISSUE TITLE
Fix Font Sizes on Resize

### ISSUE THREAD

**Issue by dewanshrawat15** [dewanshrawat15/lastofus#1]
The font size for different devices is not perfect. Fix that using media queries. PR's which cater to the requirement will be accepted.

**Comment by LarisaArmstrong** [comment]
I am working on this :)

**Comment by dewanshrawat15** [comment]
Please keep in mind that the font sizes should be well responsive on different device sizes too.

**Comment by LarisaArmstrong** [comment]
I will try my best :)

**Comment by dewanshrawat15** [comment]
@LarisaArmstrong has there been any progress?

**Comment by dewanshrawat15** [comment]
Due to no response on this issue, I'm closing this issue
