### ISSUE TITLE
Add a readme file

### ISSUE THREAD

**Issue by dewanshrawat15** [dewanshrawat15/lastofus#3]
Add a quality Readme.md file taking reference to https://github.com/dewanshrawat15/Mailing-Script

**Comment by djsteinmetz** [comment]
@dewanshrawat15 - Hi, I'm interested in helping you out with the readme file!  Could you describe to me the functionality of this repository?

**Comment by arpitjainds** [comment]
What is to be added in the ReadMe file?

**Comment by dewanshrawat15** [comment]
@arpitjainds study the repository carefully. Create a readme file according to the repo

**Comment by chiragrathi24** [comment]
I would like to work on it.

**Comment by dewanshrawat15** [comment]
Fixed in #6
